# ~/.profile: executed by the command interpreter for login shells.
# This file is not read by bash(1), if ~/.bash_profile or ~/.bash_login
# exists.
# see /usr/share/doc/bash/examples/startup-files for examples.
# the files are located in the bash-doc package.

# the default umask is set in /etc/profile; for setting the umask
# for ssh logins, install and configure the libpam-umask package.
#umask 022

# if running bash
if [ -n "$BASH_VERSION" ]; then
    # include .bashrc if it exists
    if [ -f "$HOME/.bashrc" ]; then
  . "$HOME/.bashrc"
    fi
fi

# set PATH so it includes user's private bin if it exists
if [ -d "$HOME/bin" ] ; then
    PATH="$HOME/bin:$PATH"
fi

case $- in
    *i*)
        ;;
    *)
        return;;
esac

# establish a known name for the current ssh-agent socket
if [ "$SSH_AUTH_SOCK" ]; then
  ln -sf "$SSH_AUTH_SOCK" "/tmp/ssh-agent-$USER-screen"
fi

# prompt to start a screen session
screen -ls
echo -n screen\?
read -r -n 1
echo
if [ "$REPLY" == "y" -o "$REPLY" == "Y" ]; then
  exec screen -R
fi
