development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: postgres
  password:
  database: sessionizer_development

test:
  adapter: postgresql
  encoding: unicode
  # Database does not work in GitHub Workflows if host parameter is not specified
  host: localhost
  pool: 5
  username: postgres
  password:
  database: sessionizer_test
