development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  username: sessionizer
  password: asdf1234
  database: sessionizer_development

test:
  adapter: postgresql
  encoding: unicode
  # Database does not work in GitHub Workflows if host parameter is not specified
  host: localhost
  pool: 5
  username: sessionizer
  password: asdf1234
  database: sessionizer_test
